sammykingx

HOME
REVIEWS
0X01-VARIABLES, IF, ELSE, WHILE
0x01-Variables, if, else, while
SammykingxSAMMYKINGXMARCH 18, 2023REVIEWS, LOW-LEVEL_PROGRAMMING
0x01 c project
alx c project
Spread the love
This is a task review on how i was able to tackle the 0x01 c-variables, if, else, while project in the alx-software engineering program. Prior to this time i really had no experience with programming or any programming language which for me was a draw back to some extent.

However i was determined to get myself up to speed irrespective of this which made me read and practice more often and yeah i got errors so it wasn’t rossy but i got it at last. So let’s get into the project properly.

Table of Contents
Prerequisites to this Project
Task 1 – Positive anything
Task 1- The last digit
Task 2 – Alphabet Game
Task 3 – alphaBET
Task 4 – Alphabet Soup
Task 5 – Numbers
Task 6 – Numberz
Task 7 – Smile in the mirror
Task 8 – Hexadecimal
Task 9 – Number combination
Task 10 – Two digits combination
Task 11 – 3 digits comb
Task 12 – all possible comb
Prerequisites to this Project
Know how to use an editor vi, emacs, nano etc to read and write files.
The char, int data type in c
control flow ( if, else, else if )
Loops in c ( for, while)
betty linter ( to check if your c file conforms to the ideal c code-style standard )
Task 1 – Positive anything
Here we’re asked to complete this source code in order to print whether the number stored in the variable n is positive or negative and also to ensure the following;

The output of the program should be:
The number, followed by
if the number is greater than 0: is positive
if the number is 0: is zero
if the number is less than 0: is negative
followed by a new line.
Since the number is going to be generated by the rand() and whatever number rand() generates it’s going to be subtracted from RAND_MAX / 2 and then saved in variable n this means that am only concerned with the value of n at every instance of running my c file.

Since this is through then i used the n variable as my parameter for my conditional statements as such i came up with the below code.

$ vi 0-positive_or_negative.c

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/**
* main - A test c file
* Return - 0 signifying program success
*/
int main(void)
{
	int n;

	srand(time(0));
	n = rand() - RAND_MAX / 2;

  if (n > 0)
  {
    printf("%d is positive\n", n);
  }

  else if (n == 0)
{
  printf("%d is zero\n", n);
}

  else if (n < 0)
{
  printf("%d is negative\n", n);
}

return (0);
}
~
~
Task 1- The last digit
Again we’re asked to write a program that gets the last digits of the random number been generated from the previous task. However this particular task has some constraints which is stated below;

The output of the program should be:
The string Last digit of, followed by
n, followed by
the string is, followed by
if the last digit of n is greater than 5: the string and is greater than 5
if the last digit of n is 0: the string and is 0
if the last digit of n is less than 6 and not 0: the string and is less than 6 and not 0
followed by a new line
So i knew i’ll be using some conditional statements to tackle this due to the constraints placed on the task, however what i couldn’t grab was how to get the last digit of a number. This was tricky really cause i was sure i’ll use the modulo operator in c but what should i divide with ? 1, 3, or 5.

Then used google and boom Stackoverflow came through for me where i saw i just needed to divide the variable by 10 and modulo operator gives you the remainder , so here’s my answer code in which i made use of the if, else if statements in c.

#include <stdio.h>
#include <stdlib.h>
#include <time.h>
/**
 * main - Entry point
 * author: Sammykingx
 * date:05-06-2022
 * Return: 0 (success)
*/
int main(void)
{
  int n;

  srand(time(0));
  n = rand() - RAND_MAX / 2;

  if (n % 10 > 5)
  {
    printf("Last digit 0f %d is %d and is greater than 5\n", n, n % 10);
 }

  else if (n % 10 == 0)
  {
    printf("Last digit of %d is %d and is 0\n", n, n % 10);
  }

  else if ((n % 10 < 6) && n % 10 != 0)
  {
	printf("Last digit of %d is %d and is less than 6 and not 0\n", n, n % 10);
  }
	return (0);
}
~
~
